import Head from "next/head";
import Container from "@mui/material/Container";
import Button from "@mui/material/Button";
import Stack from "@mui/material/Stack";
import { useRouter } from "next/router";
import WithoutAuth from "../HOC/withoutauth";

export default function Home() {
  const router = useRouter();
  return (
    <div style={{ padding: "0 1em" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        component="main"
        maxWidth="md"
        sx={{
          backgroundColor: "#dadada",
          marginTop: "10em",
          borderRadius: "5px",
          height: "20em",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
          gap: "3em",
        }}
      >
        <h1>Landing Page Header</h1>
        <Stack spacing={2} direction="row">
          <Button variant="outlined" onClick={() => router.push("/login")}>
            Log in
          </Button>
          <Button variant="outlined" onClick={() => router.push("/register")}>
            Sign up
          </Button>
        </Stack>
      </Container>
    </div>
  );
}

export const getServerSideProps = WithoutAuth(() => {
  return {
    props: {},
  };
});
